import net.darkhax.curseforgegradle.TaskPublishCurseForge
import net.darkhax.curseforgegradle.UploadArtifact

plugins {
    id 'dev.architectury.loom' version '1.10-SNAPSHOT'
    id "com.gradleup.shadow" version "8.3.9"
    id 'net.darkhax.curseforgegradle' version '1.1.+'
}

configurations {
    shadow
    implementation.extendsFrom(shadow)
}

shadowJar {
    configurations = [project.configurations.shadow]
    mergeServiceFiles()
    archiveClassifier = "dev-shadow"
    exclude "LICENSE_MixinExtras"
}

remapJar {
    dependsOn tasks.named("shadowJar")
    inputFile = shadowJar.archiveFile
    archiveClassifier = null
    exclude "LICENSE_MixinExtras"
}

group = project.maven_group
version = "${project.minecraft_version}-${project.mod_version}"

base {
    archivesName = project.archives_name
}

loom {
    silentMojangMappingsLicense()
}

repositories {
    maven { name = "ParchmentMC";    url = 'https://maven.parchmentmc.org' }
    maven { name = "MinecraftForge"; url = "https://files.minecraftforge.net/maven/" }
    maven { name = "NeoForged";      url = 'https://maven.neoforged.net/releases' }
    maven { name = "FabricMC";       url = "https://maven.fabricmc.net/" }
    maven { name = "Architectury";   url = "https://maven.architectury.dev/" }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content { includeGroup "maven.modrinth" }
    }
    maven {
        name = "CurseMaven"
        url = "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }
    maven {
        name = "Fuzs Mod Resources"
        url = "https://raw.githubusercontent.com/Fuzss/modresources/main/maven/"
    }
    maven {
        name = "Terraformers"
        url = "https://maven.terraformersmc.com/"
    }
}

def versionMap = [
    "1.20.1" : [fapi: "0.92.7+1.20.1"  , modmenu: "7.2.2"        , fcapi: "8.0.3"    , parchment: "2023.09.03"],
    "1.16.5" : [fapi: "0.42.0+1.16"    , modmenu: "1.16.23"      , fcapi: "1.0.2"    , parchment: "2022.03.06"],
    "1.18.2" : [fapi: "0.77.0+1.18.2"  , modmenu: "3.2.5"        , fcapi: "3.2.4"    , parchment: "2022.11.06"],
    "1.21.1" : [fapi: "0.116.9+1.21.1" , modmenu: "11.0.3"       , fcapi: "21.1.6"   , parchment: "2024.11.17"],
    "1.21.4":  [fapi: "0.119.4+1.21.4" , modmenu: "13.0.3"       , fcapi: "21.4.3"   , parchment: "2025.03.23"],
    "1.21.6":  [fapi: "0.128.2+1.21.6" , modmenu: "15.0.1"       , fcapi: "21.6.4"   , parchment: "2025.06.29"],
    "1.21.8":  [fapi: "0.136.1+1.21.8" , modmenu: "15.0.1"       , fcapi: "21.8.2"   , parchment: "2025.09.14"],
    "1.21.11": [fapi: "0.141.3+1.21.11", modmenu: "17.0.0-beta.2", fcapi: "21.11.1"  , parchment: "2025.12.20"]
]

HashMap<String, String> versionInfo = versionMap[minecraft_version]

dependencies {
    minecraft "net.minecraft:minecraft:$project.minecraft_version"
    mappings loom.layered {
        officialMojangMappings()
        parchment("org.parchmentmc.data:parchment-${project.minecraft_version}:${versionInfo.parchment}@zip")
    }

    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
    modImplementation "net.fabricmc.fabric-api:fabric-api:${versionInfo.fapi}"

    if (minecraft_version == "1.16.5" || minecraft_version == "1.18.2") {
        modApi("net.minecraftforge:forgeconfigapiport-fabric:${versionInfo.fcapi}") {
            exclude group: "net.fabricmc.fabric-api"
        }
    } else {
        modApi("fuzs.forgeconfigapiport:forgeconfigapiport-fabric:${versionInfo.fcapi}") {
            exclude group: "net.fabricmc.fabric-api"
        }
    }
    modImplementation("com.terraformersmc:modmenu:${versionInfo.modmenu}") {
        exclude group: "net.fabricmc.fabric-api"
    }

    modLocalRuntime("fuzs.forgeconfigscreens:forgeconfigscreens-fabric:8.0.2") {
        exclude group: "net.fabricmc.fabric-api"
    }
    modLocalRuntime("maven.modrinth:sparsestructures:XcUzPH3Z") {
        exclude group: "net.fabricmc.fabric-api"
    }
}

processResources {
    inputs.property 'version', project.version

    filesMatching("fabric.mod.json") {
        expand "version": inputs.properties.version
    }
}

def javaInfoMap = [
        "1.20.1":  [version  : JavaVersion.VERSION_17,  release  : 17, supported: ["Java 17", "Java 21", "Java 22"]],
        "1.16.5":  [version  : JavaVersion.VERSION_1_8, release  : 8,  supported: ["Java 8", "Java 17", "Java 21", "Java 22"]],
        "1.18.2":  [version  : JavaVersion.VERSION_17,  release  : 17,  supported: ["Java 17", "Java 21", "Java 22"]],
        "1.21.1":  [version  : JavaVersion.VERSION_21,  release  : 21, supported: ["Java 21", "Java 22"]],
        "1.21.4":  [version  : JavaVersion.VERSION_21,  release  : 21, supported: ["Java 21", "Java 22"]],
        "1.21.6":  [version  : JavaVersion.VERSION_21,  release  : 21, supported: ["Java 21", "Java 22"]],
        "1.21.8":  [version  : JavaVersion.VERSION_21,  release  : 21, supported: ["Java 21", "Java 22"]],
        "1.21.11": [version  : JavaVersion.VERSION_21,  release  : 21, supported: ["Java 21", "Java 22"]]
]

def javaInfo = javaInfoMap[minecraft_version]

java {
    withSourcesJar()
    JavaVersion javaVer = (JavaVersion) javaInfo.version
    sourceCompatibility = javaVer
    targetCompatibility = javaVer
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = (int) javaInfo.release
}

String CHANGELOG = file("CHANGELOG.md").getText("UTF-8")

tasks.register("publishCurseForge", TaskPublishCurseForge) {
    if (!cf_project_id.isEmpty()) {
        apiToken = System.getenv("CURSEFORGE_TOKEN")
        disableVersionDetection()
    
        UploadArtifact mainFile = upload(cf_project_id, remapJar)
        mainFile.displayName = "${archives_name}-${version}"
        mainFile.releaseType = "release"
        mainFile.changelog = CHANGELOG
        mainFile.changelogType = "markdown"
        mainFile.addModLoader("Fabric")
        Iterator<String> supported = javaInfo.supported.iterator()
        while (supported.hasNext()) {
            mainFile.addJavaVersion(supported.next());
        }
        mainFile.addGameVersion(minecraft_version)
    
        UploadArtifact sourcesFile = mainFile.withAdditionalFile(sourcesJar)
        sourcesFile.changelog = CHANGELOG
        sourcesFile.changelogType = "markdown"
    } else {
        System.err.println("CurseForge Project ID is not provided")
    }
}
